require 'plugins.language_support.mason-setup'
require 'plugins.language_support.lsp_autocmds'
require 'plugins.language_support.linting'
require 'plugins.language_support.formatting'
require 'plugins.language_support.treesitter'
require 'plugins.language_support.autocomplete'
require 'plugins.language_support.debug'
