#!/bin/sh

export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland

export QT_QPA_PLATFORM="wayland;xcb"
export GDK_BACKEND=wayland,x11,*
export MOZ_ENABLE_WAYLAND=1

export GTK_THEME="catppuccin-mocha-red-standard+default"
export XCURSOR_THEME=Bibata-Modern-Ice
export QT_QPA_PLATFORMTHEME=qt6ct

GPU_CONFIG="$HOME/dotfiles/scripts/env_hardware.sh"
if [ -e "$GPU_CONFIG" ]; then
    . "$GPU_CONFIG"
fi

# Start Hyprland binded with a DBus session
exec dbus-run-session Hyprland